version: "3"
services:
  mongodb:
    image: mongo:5.0
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./services/mongodb/data:/data/db:rw
    command: 
      - '--logpath'
      - '/dev/null'

  auth:
    build: ./services/auth
    ports: 
      - "3002:8080"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - BCRYPT_SALT_ROUNDS=${AUTH_BCRYPT_SALT_ROUNDS}
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3002/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  api_gateway:
    build: ./services/api_gateway
    ports: 
      - "${GATEWAY_PORT}:8080"
    environment:
      - DEBUG_LOG=true
      - AUTH_SERVICE_HOSTNAME=auth
      - LOBBY_SERVICE_HOSTNAME=lobby
      - GAME_SERVICE_HOSTNAME=game
    depends_on:
      lobby:
        condition: "service_healthy"
      # todo: add a healthchek for game and another condition
      
  lobby:
    build: ./services/lobby
    ports: 
      - "${LOBBY_PORT}:8080"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - GAME_SERVICE_HOSTNAME=game
      - DEBUG_LOG=true
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  game:
    build: ./services/game
    ports: 
      - "${GAME_PORT}:8080"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongodb

  swagger:
    build: ./services/swagger
    expose:
      - ${SWAGGER_PORT}
    ports:
      - ${SWAGGER_PORT}:8080
    depends_on:
      - api_gateway
    environment:
      - SWAGGER_JSON=/swagger.yaml