version: "3"
services:
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      # - ./services/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./services/mongodb/data:/data/db

  postgres:
    image: postgres:13.2
    # restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:13.0.0
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "28080:8080"
      - "9990:9990"

  lobby:
    build: ./services/lobby
    restart: unless-stopped
    ports: 
      - "3000:3000"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - GAME_SERVICE_HOSTNAME=game
      - PORT=3000
    depends_on:
      - mongodb

  game:
    build: ./services/game
    restart: unless-stopped
    ports: 
      - "3001:3001"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PORT=3001
    depends_on:
      - mongodb