version: "3"
services:
  mongodb:
    image: mongo:5.0
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      # - ./services/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./services/mongodb/data:/data/db
    command: 
      - '--logpath'
      - '/dev/null'

  auth:
    build: ./services/auth
    ports: 
      - "3002:3002"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PORT=3002
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - BCRYPT_SALT_ROUNDS=${AUTH_BCRYPT_SALT_ROUNDS}
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3002/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    # volumes:
      # - ./services/auth/config/jwk.json:/keys/jwk.json

  gateway:
    build: ./services/gateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - FC_ENABLE=1
      - FC_PARTIALS="./config/partials"
    depends_on:
      auth:
        condition: "service_healthy"
      
  lobby:
    build: ./services/lobby
    ports: 
      - "3000:3000"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - GAME_SERVICE_HOSTNAME=game
      - PORT=3000
    depends_on:
      - mongodb
  
  game:
    build: ./services/game
    ports: 
      - "3001:3001"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PORT=3001
    depends_on:
      - mongodb
